### ISSUE TITLE
Sign-up form - Design

### ISSUE THREAD

**Issue by Jade-ux** [Jade-ux/WomenTechConnect#16]
Design and code separated into two cards but if you find it easier to go ahead and create it in the code straight away, that's great, feel free to assign both tickets to yourself

Wireframes for inspiration:

![Image](https://user-images.githubusercontent.com/62659009/225906613-50df2a75-1447-495f-9824-a78b0b6f43f2.png)

**Comment by tanisecarvalho** [comment]
Design done as we spoke last night to keep the cards and signup separated. 

![Image](https://user-images.githubusercontent.com/15631445/226121459-04fee302-274b-4283-9e1d-a7cd57394dd1.JPG)
