### ISSUE TITLE
Sign-up form - Code

### ISSUE THREAD

**Issue by Jade-ux** [Jade-ux/WomenTechConnect#17]
Dependant on the issue 'Sign-up form - Design'

**Comment by tanisecarvalho** [comment]
Validation and redirecting to thank you page added.

**Comment by tanisecarvalho** [comment]
still missing the current status and how it will going to be used in the database. We also must align the info from the cards to the signup form

**Comment by tanisecarvalho** [comment]
As we spoke on Slack, I changed current status to areas of interest and added to the list:
Full-stack development
Front-end development
Back-end development
Dev ops

Added current role.
