### ISSUE TITLE
Research Database options

### ISSUE THREAD

**Issue by Jade-ux** [Jade-ux/WomenTechConnect#21]

**Comment by beratzorlu** [comment]
I want to take this but I don't have experience with setting up databases yet. 

But what I can say is that we used Django in my previous Hackathon project, and we deployed using PosgresSQL on Heroku.

**Comment by Jade-ux** [comment]
Hey @beratzorlu I'm happy to help with this one! I don't think we're going to be able to go with Django because most people on the team are front-endy and it would be a bit different to how they are used to working. 

Mongo DB could be a good option, I have an account set up and can definitely help set up the database.

For image storage, if we are going to allow users to add their own profiles, I'd recommend asking them to add url's to their images so that we don't have to worry about integrating with AWS (that is more overhead than is worth).

In my previous Hackathon we went with this option and it worked well.

**Comment by Jade-ux** [comment]
Using MongoDB now
