### ISSUE TITLE
Contact a mentor form - pop-up or page

### ISSUE THREAD

**Issue by Jade-ux** [Jade-ux/WomenTechConnect#71]
Link from the 'Schedule a call' button on each card
form will have drop-down of all mentor names
you can then add a message and your email address and name
when it is submitted, you'll be directed to a thank you page

**Comment by CallumDennisIE** [comment]
GoogleSheet with all of the names:
https://docs.google.com/spreadsheets/d/1nMb7MwfQ4bQtv2ghuPi4qzqQ4wiNKa9b8LbbxxfvPuI/edit#gid=0

**Comment by Jade-ux** [comment]
Drop-down field for all mentors
JC - create form & send to thank you pg when done

**Comment by beratzorlu** [comment]
I’ll help with this.

**Comment by CallumDennisIE** [comment]
Names list here:
https://docs.google.com/spreadsheets/d/1nMb7MwfQ4bQtv2ghuPi4qzqQ4wiNKa9b8LbbxxfvPuI/edit#gid=0
