### ISSUE TITLE
README: add in Javascript functionality write-up

### ISSUE THREAD

**Issue by Jade-ux** [Jade-ux/WomenTechConnect#80]

**Comment by CallumDennisIE** [comment]
## Features
### Mentor Search
In the 'Mentorship Program' section of the page there is the ability to search for a mentor based on selected criteria. Using radio buttons, users can select certain categogris, this will then limit the mentors shown, to ones that match the criteria.

The availble categroies are 'Role', 'Location', 'Skills' and 'Career Progression':

![Image](https://user-images.githubusercontent.com/110825112/226203673-f2bdb875-fa14-46d0-b822-549c873607d7.png)

Each mentor card will contain a section dedicated to content that relates to the search criteria:

![Image](https://user-images.githubusercontent.com/110825112/226203911-bf19eb92-65f7-4b26-97c8-58dd506faac1.png)
