### ISSUE TITLE
Meet the team pg

### ISSUE THREAD

**Issue by CallumDennisIE** [Jade-ux/WomenTechConnect#95]
Example: https://mariamar95.github.io/jan-hackathon/team.html

**Comment by Kieran132** [comment]
Kieran Mclean:
LinkedIn - https://www.linkedin.com/in/kieran-mclean95/
Github - https://github.com/Kieran132



![Image](https://user-images.githubusercontent.com/110598854/226208498-c3f58b8b-5357-444d-ba63-7ee916af66e8.png)

**Comment by Louibens** [comment]
https://photos.google.com/photo/AF1QipNN60h81j-9aJagOXEa6RHDoNB6YKqW2Db9DZGI
Louise Benson
LinkedIn - https://www.linkedin.com/in/louise-benson-856792150/
Github - https://github.com/Louibens

**Comment by CallumDennisIE** [comment]
https://www.linkedin.com/in/callum-dennis-ireland
https://github.com/CallumDennisIE


![Image](https://user-images.githubusercontent.com/110825112/226209069-4bdbf8d9-5aeb-42f6-b650-a211320b4e6a.JPG)

**Comment by Jade-ux** [comment]
https://www.linkedin.com/in/jade-shannon-carvalho/
https://github.com/Jade-ux



![Image](https://user-images.githubusercontent.com/62659009/226211283-66d0f093-24f7-4bc2-a577-f14fe8389878.jpg)
